<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\Patient;
use App\Models\Menu; // Perlu untuk nama dan kalori menu
use App\Services\MealRecommendationService; // <--- Impor Service Rekomendasi
use App\Models\FoodConsumption; // Perlu untuk menyimpan data
use Carbon\Carbon;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\DB; // Untuk transaksi

class AutoGenerateDailySchedules extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'schedule:auto-generate {date?}'; // date? opsional untuk generate tanggal spesifik

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Automatically generates daily food consumption schedules for active patients.';

    protected $mealRecommendationService;

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct(MealRecommendationService $mealRecommendationService)
    {
        parent::__construct();
        $this->mealRecommendationService = $mealRecommendationService;
    }

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $date = $this->argument('date') ? Carbon::parse($this->argument('date')) : Carbon::tomorrow(); // Default besok
        $dateString = $date->toDateString();

        $this->info("Starting automatic schedule generation for: " . $dateString);
        Log::info("AutoGenerateDailySchedules: Starting generation for {$dateString}.");

        $activePatients = Patient::where('status_pasien', 'aktif')->get();
        $totalGeneratedSlots = 0;
        $failedPatients = []; // Untuk pasien yang gagal genrate

        if ($activePatients->isEmpty()) {
            $this->info("No active patients found. Exiting.");
            Log::info("AutoGenerateDailySchedules: No active patients found.");
            return Command::SUCCESS;
        }

        // Opsi waktu makan yang akan dijadwalkan
        $waktuMakanOptions = ['pagi', 'selingan_pagi', 'siang', 'selingan_siang', 'sore', 'selingan_sore'];

        foreach ($activePatients as $patient) {
            DB::beginTransaction();
            try {
                // Muat relasi yang dibutuhkan oleh service
                $patient->load('standarDiit', 'dietKhusus');

                foreach ($waktuMakanOptions as $waktuMakan) {
                    $recommendations = $this->mealRecommendationService->getRecommendedMenusForSlot(
                        $patient,
                        $dateString,
                        $waktuMakan
                    );

                    $chosenMenuId = null;
                    $chosenMenuName = null; // Tambahkan untuk logging lebih baik
                    
                    // === KOREKSI LOGIKA PEMILIHAN MENU TERBAIK ===
                    // Hanya pilih menu jika suitability-nya 'suitable'.
                    // Jika tidak ada yang 'suitable', jangan pilih menu sama sekali untuk slot ini.
                    $bestSuitableRecommendation = collect($recommendations)->first(fn($rec) => $rec['suitability'] === 'suitable');
                    
                    if ($bestSuitableRecommendation) {
                        $chosenMenuId = $bestSuitableRecommendation['menu']['id'];
                        $chosenMenuName = $bestSuitableRecommendation['menu']['nama'];
                        Log::info("AutoGenerateDailySchedules: Memilih menu '{$chosenMenuName}' (ID: {$chosenMenuId}) untuk pasien {$patient->id} pada {$dateString}, waktu {$waktuMakan}.");
                    } else {
                        Log::info("AutoGenerateDailySchedules: Tidak ada menu 'suitable' ditemukan untuk pasien {$patient->nama_pasien} (ID: {$patient->id}) pada tanggal {$dateString}, waktu {$waktuMakan}. Rekomendasi: " . json_encode($recommendations));
                        // Anda bisa tambahkan warning ke failedPatients jika ingin mencatat slot kosong ini.
                    }
                    // ===========================================

                    if ($chosenMenuId) {
                        $chosenMenu = Menu::find($chosenMenuId); // Ambil model menu
                        // ... (sisa logika updateOrCreate yang sudah ada) ...
                    } else {
                        Log::info("AutoGenerateDailySchedules: Slot untuk pasien {$patient->nama_pasien} (ID: {$patient->id}) pada tanggal {$dateString}, waktu {$waktuMakan} dibiarkan kosong karena tidak ada rekomendasi yang cocok.");
                    }
                } // End foreach waktuMakan

                DB::commit();
                $this->info("Generated schedule for patient: " . $patient->nama_pasien);
            } catch (\Exception $e) {
                DB::rollBack();
                $this->error("Failed to generate schedule for patient: " . $patient->nama_pasien . " - " . $e->getMessage());
                Log::error("AutoGenerateDailySchedules: Failed for patient {$patient->nama_pasien} (ID: {$patient->id}) - {$e->getMessage()} at {$e->getFile()}:{$e->getLine()}");
                $failedPatients[] = $patient->nama_pasien;
            }
        } // End foreach activePatients

        $this->info("Completed automatic schedule generation. Total slots generated: " . $totalGeneratedSlots);
        if (!empty($failedPatients)) {
            $this->warn("Failed to generate schedules for some patients: " . implode(', ', $failedPatients));
        }
        Log::info("AutoGenerateDailySchedules: Finished generation. Total slots generated: {$totalGeneratedSlots}. Failed patients: " . implode(', ', $failedPatients));

        return Command::SUCCESS;
    }
}