<?php

namespace App\Console;

use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;
use App\Console\Commands\GenerateDailyFoodConsumptions;
use App\Console\Commands\AutoGenerateDailySchedules;
use App\Console\Commands\DeductDailyStock;

class Kernel extends ConsoleKernel
{
    /**
     * Define the application's command schedule.
     */

     protected $commands = [
        GenerateDailyFoodConsumptions::class, // Tambahkan ini
        AutoGenerateDailySchedules::class,
    ];
    protected function schedule(Schedule $schedule): void
    {
        // $schedule->command('inspire')->hourly();
        $schedule->command('generate:daily-food-consumptions')->dailyAt('00:00');
        $schedule->command(AutoGenerateDailySchedules::class)->dailyAt('00:00');
        $schedule->command(DeductDailyStock::class)->dailyAt('01:00');
    }

    /**
     * Register the commands for the application.
     */
    protected function commands(): void
    {
        $this->load(__DIR__.'/Commands');

        require base_path('routes/console.php');
    }
}
